### ISSUE TITLE
Numeric comparison used with string values

### ISSUE THREAD

**Issue by kravciak** [yast/yast-users#141]
https://github.com/yast/yast-users/blob/master/src/modules/Users.pm#L4067 uses "==" instead of "eq" for string comparison.

Argument "imported" isn't numeric in numeric eq (==) at /usr/share/YaST2/modules/Users.pm line 4067
(W numeric) The indicated string was fed as an argument to an operator
that expected a numeric value instead.  If you're fortunate the message
will identify which operator was so unfortunate.

**Comment by mvidner** [comment]
Ha, I've found two more bugs like this!

```pl
$ find -name \*.pm | xargs grep '== "'

./yast/yast-samba-server/src/modules/SambaPrinters.pm:    if( name == "printers" ) 
./yast/yast-samba-server/src/modules/YaPI/Samba.pm:    $role = "STANDALONE" if $role == "MEMBER";
./yast/yast-samba-server/src/modules/SambaBackendLDAP.pm:    # bind with common dn (== "ldap admin dn") and secret.tdb LDAP_BIND_PW password (via LDAP module)
./yast/yast-users/src/modules/Users.pm:        if ($user{"modified"} == "imported") {
```

**Comment by kravciak** [comment]
Moved to https://bugzilla.suse.com/show_bug.cgi?id=1029528
