### ISSUE TITLE
The option/feature to encrypt use home directory no longer available since Leap 15.0?

### ISSUE THREAD

**Issue by ace4dude** [yast/yast-users#165]
It looks like the option/feature to encrypt use home directories is no longer available on YaST2 for leap 15.x KDE environment, but I checked the user document that there's still a section describing how to enable encrypting user home directory by a check box.  Just wonder if the option is intentionally taken off from YaST2 or by an accident.

**Comment by dgdavid** [comment]
Hi there!

The support for encrypting the home directory [was dropped in `yast-users 4.0.0`](https://github.com/yast/yast-users/pull/149), back in Nov 8, 2017. Some remaining dead code was also [removed more recently](https://github.com/yast/yast-users/pull/198) in Feb 27, 2019.

Please, bear in mind the note in the original PR:

> don't get confused by 'encrypted', which states whether a password is already encrypted

By the time being I'm going to close the issue, but it would be nice if you can provide links to the user documentation that you checked.

Thank you!

**Comment by dgdavid** [comment]
BTW, I hope you can forgive us for the long delay answering here.
