### ISSUE TITLE
Failed openQA tests with 4.6.3

### ISSUE THREAD

**Issue by ana** [yast/yast-users#389]
There a couple of issues in openQA after the upload of 4.6.3 on July 24.
Please see:

https://openqa.opensuse.org/tests/3455534#step/enable_autologin/3

https://openqa.opensuse.org/tests/3455439#step/firstrun/5

**Comment by shundhammer** [comment]
https://confluence.suse.com/display/YAST/How+to+Write+a+Good+Bug+Report

**Comment by ana** [comment]
Fixed https://github.com/yast/yast-firstboot/pull/146

@shundhammer Please, be more security minded and don't share private URLs in public forums.

**Comment by shundhammer** [comment]
This is not at all private. It's an internal copy of a document that we also have available on a public site.

Did you read the document?

**Comment by shundhammer** [comment]
Anyway, YaST bugs are handled in Bugzilla. All our workflows are set up for that.
