### ISSUE TITLE
yast-users fails to build in SLE-15-SP6

### ISSUE THREAD

**Issue by shundhammer** [yast/yast-users#396]
This became visible with PR #395 : 

The unit tests of yast-users are failing when trying to build in a SLE-15-SP6 environment:

https://github.com/yast/yast-users/actions/runs/10471706681/job/29001887903?pr=395

```
  1) Y2Users::Clients::Auto#run Import when double users have been given in the profile report error
     Failure/Error: expect(subject.run).to eq(true)

     NoMethodError:
make[3]: *** [Makefile:627: test-suite.log] Error 1
make[2]: *** [Makefile:735: check-TESTS] Error 2
       undefined method `Import' for Yast::Users:Module
     # /usr/src/packages/BUILD/yast2-users-4.6.5/src/lib/users/clients/auto.rb:67:in `import'
     # /usr/share/YaST2/lib/installation/auto_client.rb:62:in `run'
     # ./lib/users/clients/auto_test.rb:42:in `block (5 levels) in <top (required)>'

  2) Y2Users::Clients::Auto#run Summary returns the users summary
     Failure/Error: allow(Yast::Users).to receive(:Summary).and_return("summary")
       Yast::Users does not implement: Summary
     # ./lib/users/clients/auto_test.rb:143:in `block (4 levels) in <top (required)>'

  3) Y2Users::Clients::Auto#run Export exports all users and groups
     Failure/Error:
       allow(Yast::Users).to receive(:Export).with("default")
         .and_return(all_users)

       Yast::Users does not implement: Export
     # ./lib/users/clients/auto_test.rb:160:in `block (4 levels) in <top (required)>'
```

And that is not limited to PR #395, it's the same with the unchanged code before that PR; and it also fails when calling that test from the command line, both with `rake test:unit` and with each one individually. It also fails with `rake osc:build` in the previous `SLE-15-SP6` branch.

All of the above work fine with `SLE-15-SP5`, though.

**Comment by shundhammer** [comment]
Possibly related according to @jreidinger : #385

**Comment by shundhammer** [comment]
@jreidinger , @mvidner : FYI

**Comment by jreidinger** [comment]
fix should be backport of https://github.com/yast/yast-users/pull/382/commits/edd88feef0de548b58596a8e7d7be160ee616513 and https://github.com/yast/yast-users/pull/382/commits/9b146a01c5ae8abcaf90020f5394bd6d36831034 otherwise there is collision of Yast::Users namespace and object that comes from perl Users module.

**Comment by shundhammer** [comment]
PR #397 fixes this.
